name: 需求-模板
description: 请使用opensourceways社区需求Issue模板提交需求创建。
title: "[需求]: "
labels: ["enhancement"]
type: "Enhancement"
body:
  - type: markdown
    attributes:
      value: |
        感谢您为社区贡献新需求！请按照以下提示提供详细信息，以便我们更好地理解并跟进。

  - type: textarea
    attributes:
      label: 需求属性
      value: |
        ## 【需求背景】

        
        ## 【需求价值】


        ## 【需求详情】



    validations:
      required: true
